ansible_python_interpreter: /usr/bin/python3

kubernetes_version: v1.10.2

kubernetes_cluster_cidr: 10.200.0.0/16
kubernetes_cluster_iprange: 10.32.0.0/24
kubernetes_cluster_dns: 10.32.0.10

kubernetes_public_address: 172.16.2.201

ansible_user: vagrant
