- name: Copy ClusterRole and ClusterRoleBinding for kube-apiserver accessing kubelets
  copy:
    src: "{{ item }}"
    dest: /etc/kubernetes/config/
  with_items:
    - rbac-cluster-role.yaml
    - rbac-cluster-role-binding.yaml
  when: inventory_hostname == "master-0"

- name: Apply ClusterRole and ClusterRoleBinding for kube-apiserver accessing kubelets
  shell: "kubectl apply --kubeconfig /vagrant/configurationfiles/admin.kubeconfig -f {{ item }}"
  with_items:
    - /etc/kubernetes/config/rbac-cluster-role.yaml
    - /etc/kubernetes/config/rbac-cluster-role-binding.yaml
  when: inventory_hostname == "master-0"
