---
language: python
python: "2.7"

# Use the new container infrastructure
sudo: false

# Install ansible
addons:
  apt:
    packages:
    - python-pip

install:
  # Install ansible
  - pip install ansible

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg

script:
  # Basic playbook syntax check
  - ansible-playbook k8s-certs-and-config.yml -i hosts --syntax-check
  - ansible-playbook k8s-master-nodes.yml -i hosts --syntax-check
  - ansible-playbook k8s-worker-nodes.yml -i hosts --syntax-check
  - ansible-playbook k8s-external-access.yml -i hosts --syntax-check

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
