- hosts: all
  become: yes
  vars:
    kubernetes_public_address: 172.16.2.201
  roles:
    - apt-updates

- hosts: init
  become: yes
  roles:
    - certificates
    - lb
    - configurationfiles
    - encryption

- hosts: master
  become: yes
  roles:
    - etcd
