- hosts: master-0
  become: yes
  roles:
    - { role: kubedns, tags: kubedns }
    - { role: dashboard, tags: dashboard }

- hosts: external
  roles:
    - { role: lb, tags: lb }
    - { role: kubectl-client, tags: kubectl-client }
