- hosts: master
  become: yes
  roles:
  - { role: etcd, tags: etcd }
  - { role: k8s-master, tags: k8s-master }
  - { role: rbac, tags: rbac }

- hosts: external
  become: yes
  roles:
  - { role: lb, tags: lb }
