- hosts: all
  become: yes
  tasks:
  - name: Update apt
    apt:
      update_cache: yes
    tags: update

- hosts: init
  become: yes
  roles:
    - { role: certificates, tags: certificates }
    - { role: configurationfiles, tags: configurationfiles }
    - { role: encryption, tags: encryption }
