- hosts: all
  become: yes
  roles:
    - update-apt

- hosts: init
  become: yes
  roles:
    - { role: certificates, tags: certificates }
    - { role: configurationfiles, tags: configurationfiles }
    - { role: encryption, tags: encryption }
