- hosts: master-0
  become: yes
  roles:
    - { role: smoke-test, tags: smoketest }

- hosts: external
  become: yes
  roles:
    - { role: kubectl-remote-access, tags: kubectl }

- hosts: master-0
  become: yes
  roles:
  - { role: dashboard, tags: dashboard }