- hosts: worker
  become: yes
  roles:
    - { role: fix-ubuntu-dns, tags: fixubuntu }
    - { role: k8s-worker, tags: k8s-worker }

- hosts: master-0
  become: yes
  roles:
    - { role: verify-worker, tags: verify }
    - { role: kubedns, tags: kubedns }
