- hosts: all
  become: yes
  vars:
    kubernetes_public_address: 172.16.2.201
  roles:
    - apt-updates

- hosts: client
  become: yes
  roles:
    - certificates
    - controller-lb
    - configurationfiles
    - encryption

- hosts: k8s-node
  become: yes
  roles:
    - docker

- hosts: controller
  become: yes
  roles:
    - etcd

- hosts: worker
