- hosts: all
  become: yes
  roles:
    - apt-updates

- hosts: k8s-node
  become: yes
  roles:
    - docker

- hosts: controller

- hosts: worker

- hosts: client
  become: yes
  roles:
    - certificates
    - controller-lb
