- hosts: worker
  become: yes
  roles:
    - worker

- hosts: controller-0
  tasks:
    - name: verify workers
      shell: kubectl get nodes --kubeconfig /vagrant/configurationfiles/admin.kubeconfig
      register: result
      until: result.stdout.find("Ready") != -1
      retries: 5
      delay: 10

    - name: Kelly said so
      debug:
        msg: "{{ result.stdout_lines }}"

- hosts: controller-0
  become: yes
  roles:
    - { role: flannel, tags: flannel }

- hosts: worker-0
  tasks:
    - name: Verify if flannel is added as network interface
      shell: ip addr
      register: ip_addr_result
      until: ip_addr_result.stdout.find("flannel.1") != -1
      retries: 5
      delay: 10
      tags: flannel

    - name: Kelly didnt say so, Motherf****
      debug:
        msg: "{{ ip_addr_result.stdout_lines }}"
      tags: flannel

- hosts: controller-0
  become: yes
  roles:
    - { role: kubedns, tags: kubedns }