# Implements https://github.com/kelseyhightower/kubernetes-the-hard-way/blob/master/docs/05-kubernetes-configuration-files.md

# But first kubectl: https://kubernetes.io/docs/tasks/tools/install-kubectl/#install-with-snap-on-ubuntu
- name: Install kubectl
  shell: "snap install kubectl --classic"

- name: ensure dirs exist
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - /vagrant/configurationfiles

- name: Generate a kubeconfig file Step 1 - kubectl config set-cluster
  shell:
   'kubectl config set-cluster kubernetes-the-hard-way \
        --certificate-authority=/vagrant/certificates/ca.pem \
        --embed-certs=true \
        --server=https://{{ item.server }}:6443 \
        --kubeconfig={{ item.name }}.kubeconfig'
  args:
    chdir: /vagrant/configurationfiles
  with_items: "{{ kubernetes_components }}"

- name: Generate a kubeconfig file Step 2 - kubectl config set-credentials
  shell:
   'kubectl config set-credentials system:node:{{ item.name }} \
        --client-certificate=/vagrant/certificates/{{ item.name }}.pem \
        --client-key=/vagrant/certificates/{{ item.name }}-key.pem \
        --embed-certs=true \
        --kubeconfig={{ item.name }}.kubeconfig'
  args:
    chdir: /vagrant/configurationfiles
  with_items: "{{ kubernetes_components }}"

- name: Generate a kubeconfig file Step 3 - kubectl config set-context
  shell:
   'kubectl config set-context default \
        --cluster=kubernetes-the-hard-way \
        --user=system:node:{{ item.name }} \
        --kubeconfig={{ item.name }}.kubeconfig'
  args:
    chdir: /vagrant/configurationfiles
  with_items: "{{ kubernetes_components }}"

- name: Generate a kubeconfig file Step 4 - kubectl config use-context
  shell: "kubectl config use-context default --kubeconfig={{ item.name }}.kubeconfig"
  args:
    chdir: /vagrant/configurationfiles
  with_items: "{{ kubernetes_components }}"