# Implements https://github.com/kelseyhightower/kubernetes-the-hard-way/blob/master/docs/05-kubernetes-configuration-files.md

# But first kubectl: https://kubernetes.io/docs/tasks/tools/install-kubectl/#install-with-snap-on-ubuntu
- name: Install kubectl
  shell: "snap install kubectl --classic"

- name: ensure dirs exist
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - /vagrant/configurationfiles

# Represents the files created with `kubectl config`
- name: create kubeconfig files
  template:
    src: kubeconfig.yaml.j2
    dest: /vagrant/configurationfiles/{{ item.name }}.kubeconfig
  with_items: "{{ kubernetes_components }}"
