- name: configure /snap/bin/kubectl
  shell: |
    /snap/bin/kubectl config set-cluster default-cluster \
      --server=https://external.k8s:6443 \
      --certificate-authority=/vagrant/certificates/ca.pem && \
    /snap/bin/kubectl config set-credentials default-admin \
      --certificate-authority=/vagrant/certificates/ca.pem \
      --client-certificate=/vagrant/certificates/admin.pem \
      --client-key=/vagrant/certificates/admin-key.pem && \
    /snap/bin/kubectl config set-credentials default-admin \
      --certificate-authority=/vagrant/certificates/ca.pem \
      --client-certificate=/vagrant/certificates/admin.pem \
      --client-key=/vagrant/certificates/admin-key.pem && \
    /snap/bin/kubectl config set-context default-system --cluster=default-cluster --user=default-admin && \
    /snap/bin/kubectl config use-context default-system
