# Implements https://github.com/kelseyhightower/kubernetes-the-hard-way/blob/master/docs/05-kubernetes-configuration-files.md

# But first kubectl: https://kubernetes.io/docs/tasks/tools/install-kubectl/#install-with-snap-on-ubuntu
- name: Install kubectl
  shell: "snap install kubectl --classic"

- name: Ensure that configuration directory exists
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - /vagrant/configurationfiles

# Represents the files created with `kubectl config`
- name: Template all kubeconfig files
  template:
    src: kubeconfig.yaml.j2
    dest: /vagrant/configurationfiles/{{ item.name }}.kubeconfig
  with_items:
    - { name: worker-0, server: "{{ kubernetes_public_address}}" }
    - { name: worker-1, server: "{{ kubernetes_public_address}}" }
    - { name: worker-2, server: "{{ kubernetes_public_address}}" }
    - { name: kube-proxy, server: "{{ kubernetes_public_address}}" }
    - { name: kube-controller-manager, server: '127.0.0.1' }
    - { name: kube-scheduler, server: '127.0.0.1' }
    - { name: admin, server: '127.0.0.1' }
