# Implements https://github.com/kelseyhightower/kubernetes-the-hard-way/blob/master/docs/05-kubernetes-configuration-files.md

# But first kubectl: https://kubernetes.io/docs/tasks/tools/install-kubectl/#install-with-snap-on-ubuntu
- name: Install kubectl
  shell: "snap install kubectl --classic"

- name: Always purge configuration directory first - otherwise old certs are used. Ignored, if ran the first time.
  file:
    path: "{{ item }}"
    state: absent
  ignore_errors: true
  with_items:
  - /vagrant/configurationfiles

- name: Ensure that configuration directory exists
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - /vagrant/configurationfiles

# Represents the files created with `kubectl config`
- name: Template all kubeconfig files
  template:
    src: kubeconfig.yaml.j2
    dest: /vagrant/configurationfiles/{{ item.name }}.kubeconfig
  with_items:
    - { name: worker-0,                prefix: 'system:node:', server: "{{ kubernetes_public_address}}" }
    - { name: worker-1,                prefix: 'system:node:', server: "{{ kubernetes_public_address}}" }
    - { name: worker-2,                prefix: 'system:node:', server: "{{ kubernetes_public_address}}" }
    - { name: kube-proxy,              prefix: 'system:',      server: "{{ kubernetes_public_address}}" }
    - { name: kube-controller-manager, prefix: 'system:',      server: '127.0.0.1' }
    - { name: kube-scheduler,          prefix: 'system:',      server: '127.0.0.1' }
    - { name: admin,                   prefix: '',             server: '127.0.0.1' }
