- name: install package
  apt:
    name: flannel

- name: Set flannel network conf on etcd
  uri:
    client_cert: /var/lib/kubelet/{{ ansible_hostname }}.pem
    client_key: /var/lib/kubelet/{{ ansible_hostname }}-key.pem
    validate_certs: no
    url: https://controller-0.k8s:2379/v2/keys/kubernetes-cluster/network/config
    body: "value={{ etcd_net_config }}"
    status_code: 200,201
    method: PUT
    return_content: yes
  run_once: true

- name: Copy flannel systemd unit file
  template:
    src: flannel.service.j2
    dest: /lib/systemd/system/flannel.service

- name: restart flannel
  systemd:
    daemon_reload: yes
    enabled: yes
    name: flannel
    state: restarted

- name: restart docker
  systemd:
    daemon_reload: yes
    enabled: yes
    name: docker
    state: restarted
