- name: Install flannel package
  apt:
    name: flannel
    update_cache: yes

- name: Copy flannel systemd unit file
  template:
    src: flannel.service.j2
    dest: /lib/systemd/system/flannel.service

- name: Restart flannel
  systemd:
    daemon_reload: yes
    enabled: yes
    name: flannel
    state: restarted

- name: Verify if flannel is added as network interface
  shell: ip addr
  register: ip_addr_result
  until: ip_addr_result.stdout.find("flannel.1") != -1
  retries: 5
  delay: 10
  tags: network
  run_once: true

- name: Show, if network interface flannel.1 was created
  debug:
    msg: "{{ ip_addr_result.stdout_lines }}"
  tags: network
  run_once: true

