- name: Set flannel network conf on etcd
  uri:
    client_cert: /var/lib/kubelet/{{ ansible_hostname }}.pem
    client_key: /var/lib/kubelet/{{ ansible_hostname }}-key.pem
    validate_certs: no
    url: https://master-0.k8s:2379/v2/keys/kubernetes-cluster/network/config
    body:
      'value={"Network": "{{ kubernetes_cluster_cidr }}",
         "SubnetLen": 24,
         "Backend": {
             "Type": "vxlan",
             "VNI": 1
         }
       }'
    status_code: 200,201
    method: PUT
    return_content: yes
  run_once: true

- name: install package
  apt:
    name: flannel

- name: Copy flannel systemd unit file
  template:
    src: flannel.service.j2
    dest: /lib/systemd/system/flannel.service

- name: restart flannel
  systemd:
    daemon_reload: yes
    enabled: yes
    name: flannel
    state: restarted

# Configure flannel-flavoured Docker systemd service
- name: Copy Docker systemd unit file
  template:
    src: docker.service.j2
    dest: /lib/systemd/system/docker.service


