# see https://github.com/kelseyhightower/kubernetes-the-hard-way/blob/master/docs/13-smoke-test.md#deployments
- name: Delete nginx deployment, if already there
  shell: kubectl delete deployment.apps/nginx -n default
  ignore_errors: true

- name: Create a nginx deployment
  shell: kubectl run nginx --image=nginx:stable

- name: Check if nginx deployment is running
  shell: kubectl get pods -l run=nginx
  register: nginx_result
  until: nginx_result.stdout.find("Running") != -1
  retries: 10
  delay: 10

- name: Show nginx kubectl get output
  debug:
    msg: "{{ nginx_result.stdout_lines }}"

# Check Service accessability
- name: Delete nginx service, if already there
  shell: kubectl delete service/nginx -n default
  ignore_errors: true

- name: Create a nginx service
  shell: kubectl expose deployment nginx --port 80 --type NodePort

# Extract Nginx Node port
- name: Gather nginx node facts
  shell: "{% raw %} kubectl get svc nginx --output=jsonpath='{range .spec.ports[0]}{.nodePort}' {% endraw %}"
  register: nginx_nodeport_result

- debug:
    msg: "The nginx nodePort is: {{ nginx_nodeport_result.stdout }}"

- name: Make an HTTP request using the external IP address and the nginx node port
  uri:
    url: "http://worker-0.k8s:{{ nginx_nodeport_result.stdout }}"
  register: worker_result
  until: worker_result.status == 200
  retries: 5
  delay: 5

- name: Response from nginx
  debug:
    msg: "{{ worker_result }}"

