- name: install cfssl
  apt:
    name: golang-cfssl

- name: ensure dirs exist
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - /vagrant/certificates
    - /opt/cfssl-config/ca
    - /opt/cfssl-config/admin

- name: copy cfssl config files
  copy:
    src: "{{ item }}"
    dest: "/opt/cfssl-config/{{ item }}"
  with_items:
    - ca-config.json

- name: create cfssl config files
  template:
    src: "templates/csr.json.j2"
    dest: "/opt/cfssl-config/{{ item }}-csr.json"
  with_items:
    - ca
    - admin

- name: generate ca keys
  shell: cfssl gencert -initca /opt/cfssl-config/ca-csr.json | cfssljson -bare ca
  args:
    chdir: /vagrant/certificates
    creates: /vagrant/certificates/ca-key.pem

- name: generate admin keys
  shell: "cfssl gencert -ca=ca.pem -ca-key=ca-key.pem -config=/opt/cfssl-config/ca-config.json -profile=kubernetes /opt/cfssl-config/{{ item }}-csr.json | cfssljson -bare {{ item }}"
  args:
    chdir: /vagrant/certificates
    creates: "/vagrant/certificates/{{ item }}-key.pem"
  with_items:
    - admin
