# see https://github.com/kelseyhightower/kubernetes-the-hard-way/blob/master/docs/12-dns-addon.md
- name: ensure directories exist
  file:
    path: /opt/kubedns
    state: directory

- name: copy kube-dns.yaml
  copy:
    src: kube-dns.yaml
    dest: /opt/kubedns/kube-dns.yaml

- name: apply kube-dns Service, ServiceAccount, ConfigMap, Deployment
  shell: kubectl apply -f /opt/kubedns/kube-dns.yaml
  register: apply_kubedns_result

- name: Result of apply kube-dns
  debug:
    msg: "{{ apply_kubedns_result.stdout_lines }}"

# Verification steps
- name: Verify kube-dns configuration
  shell: kubectl get pods -l k8s-app=kube-dns -n kube-system
  register: kubedns_result
  until: kubedns_result.stdout.find("Running") != -1
  retries: 5
  delay: 10

- name: Kelly said so
  debug:
    msg: "{{ kubedns_result.stdout_lines }}"

- name: Create a busybox deployment
  shell: kubectl run busybox --image=busybox --command -- sleep 3600

- name: Create a busybox deployment
  shell: kubectl get pods -l run=busybox
  register: busybox_result

- name: get pods output
  debug:
    msg: "{{ busybox_result.stdout_lines }}"